[package]
name = "fastnbt"
description = "Minecraft NBT (and more) parser aiming for high speed parsing."
repository = "https://github.com/owengage/fastnbt"
readme = "README.md"
version = "0.7.0"
authors = ["Owen Gage <owengage@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
flate2 = "1.0.14"
num_enum = "0.5.0"
byteorder = "1.3.4"
bit_field = "0.10.0"
serde = { version = "1.0" }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"]}