[package]
name = "fastnbt"
description = "Minecraft NBT (and more) parser aiming for high speed parsing."
repository = "https://github.com/owengage/fastnbt"
readme = "README.md"
version = "0.13.0"
authors = ["Owen Gage <owengage@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
byteorder = "1.3"
serde = { version = "1.0", features = [ "derive" ] }

[dev-dependencies]
flate2 = "1.0"
