[package]
name = "fastnbt"
description = "Minecraft NBT (and more) parser aiming for high speed parsing."
repository = "https://github.com/owengage/fastnbt"
version = "0.4.0"
authors = ["Owen Gage <owengage@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
num_enum = "0.5.0"
byteorder = "1"
rayon = "1.3.0"
bit_field = "0.10.0"
image = "0.23.4"