[package]
name = "fastnbt"
description = "Minecraft NBT (and more) parser aiming for high speed parsing."
repository = "https://github.com/owengage/fastnbt"
readme = "README.md"
version = "0.10.0"
authors = ["Owen Gage <owengage@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
num_enum = "0.5"
byteorder = "1.3"
bit_field = "0.10"
serde = "1.0"

[dev-dependencies]
flate2 = "1.0"
